export const TECH_DESCRIPTIONS = {
  'Power Apps': 'Plataforma low-code da Microsoft para criar apps web e mobile integrados a dados corporativos.',
  'Power Automate': 'Automatiza fluxos de trabalho entre aplicações e serviços sem necessidade de código.',
  'Azure DevOps': 'Suite Microsoft para CI/CD, gestão de projetos e controle de versão.',
  'Gherkin (BDD)': 'Linguagem legível por humanos para descrever comportamentos em testes BDD.',
  'SQL': 'Linguagem padrão para consulta e manipulação de bancos de dados relacionais.',
  'Microsoft Teams': 'Plataforma de comunicação e colaboração corporativa da Microsoft.',
  'SharePoint': 'Plataforma Microsoft para gestão de documentos e intranets corporativas.',
  'C#': 'Linguagem orientada a objetos da Microsoft, base do ecossistema .NET.',
  '.NET': 'Framework multiplataforma para desenvolvimento de apps web, mobile e desktop.',
  'Angular': 'Framework TypeScript do Google para SPAs com arquitetura baseada em componentes.',
  'Git': 'Sistema de controle de versão distribuído para rastrear mudanças no código.',
  'Power BI': 'Ferramenta de BI da Microsoft para criação de dashboards e relatórios interativos.',
  'Power Query': 'ETL visual da Microsoft para extração e transformação de dados sem código.',
  'DAX': 'Linguagem de fórmulas do Power BI e Analysis Services para cálculos analíticos.',
  'Python': 'Linguagem principal do ecossistema de dados, automação e machine learning.',
  'JavaScript': 'Linguagem de programação web, base do ecossistema frontend e Node.js.',
  'PySpark': 'API Python para Apache Spark — processamento distribuído de grandes volumes de dados.',
  'Microsoft Fabric': 'Plataforma unificada da Microsoft para engenharia de dados, analytics e BI em nuvem.',
  'Azure SQL': 'Banco de dados relacional gerenciado na nuvem Azure, baseado no SQL Server.',
  'Azure Data Lake': 'Armazenamento escalável na nuvem para dados estruturados e não estruturados.',
  'ETL': 'Extração, Transformação e Carga de dados entre sistemas e pipelines.',
  'Next.js': 'Framework React da Vercel para renderização híbrida (SSR/SSG) de aplicações web.',
  'APIs REST': 'Comunicação entre sistemas usando HTTP e princípios RESTful.',
  'Scrum': 'Framework ágil com sprints, cerimônias e entregas incrementais.',
  'Azure': 'Plataforma de nuvem da Microsoft para computação, dados, IA e DevOps.',
  'BDD': 'Behavior Driven Development — testes orientados ao comportamento de negócio.',
  'QA': 'Quality Assurance — garantia de qualidade por meio de testes e validações.',
  'Data Migration': 'Transferência e transformação de dados entre sistemas ou estruturas.',
  'T-SQL': 'Extensão do SQL usada no SQL Server e Azure SQL com suporte a stored procedures.',
  'Postman': 'Ferramenta para teste e documentação de APIs REST com interface visual.',
  'Excel': 'Planilha Microsoft para análise de dados, automação via fórmulas e relatórios.',
  'Jira': 'Plataforma Atlassian para gestão ágil, bugs e sprints.',
  'Fabric': 'Microsoft Fabric — plataforma unificada de dados e analytics em nuvem.',
  'Gherkin': 'Linguagem legível por humanos para descrever comportamentos em testes BDD.',
  'Power Platform': 'Conjunto de ferramentas Microsoft low-code: Power Apps, Power Automate e Power BI.',
  'HTML': 'Linguagem de marcação para estruturação de páginas e interfaces web.',
  'CSS': 'Linguagem de estilo para layout, cores e animações em interfaces web.',
  'Data Factory': 'Serviço Azure de orquestração e integração de dados (ETL/ELT) em pipelines.',
  'MSSQL': 'Microsoft SQL Server — banco de dados relacional amplamente usado em ambientes corporativos.',
  'Make': 'Plataforma de automação low-code para integração entre apps e fluxos sem código.',
  'Kommo': 'CRM conversacional com suporte a automações e integração com canais de mensageria.',
  'RD Station': 'Plataforma brasileira de marketing digital e automação de campanhas.',
  'RD Conversas': 'Ferramenta RD para gestão de atendimento multicanal via chat e WhatsApp.',
  'WhatsApp API': 'API oficial do WhatsApp Business para integração de mensagens em sistemas e automações.',
  'SAP': 'Sistema ERP corporativo para gestão de processos operacionais e logísticos.',
  'Azure Database': 'Serviço gerenciado de banco de dados relacional na nuvem Microsoft Azure.',
  'WareHouse': 'Microsoft Fabric Warehouse — banco de dados analítico em nuvem para consultas SQL em escala.',
  'DataLake': 'Microsoft Fabric Data Lake — armazenamento hierárquico de arquivos para dados brutos e processados.',
  'Máquinas virtuais Azure': 'VMs na nuvem Azure para executar workloads customizados com controle total do ambiente.',
  'Excalidraw': 'Ferramenta de diagramação colaborativa com estilo de esboço para arquitetura e fluxos.',
};
